### ISSUE TITLE
Documentation of training on Emotion

### ISSUE THREAD

**Issue by chiragsanghvi10** [kiri-ai/kiri#6]
Hi, 

First of all thanks a ton for this repository, the results that I am looking for is quite promising without any down-stream task training. :)

Are you planning to publish the paper/documentation on the data T5 is trained for emotion ? 

Best,
Chirag Sanghvi

**Comment by ojasaar** [comment]
Hey Chirag,

Firstly, thanks a lot for the feedback.

Our T5 model is jointly trained on Squad 2.0, CoQa, CNN/DailyMail summarisation and GoEmotions. We use it for the qa, summarisation and emotion methods.

You can find the GoEmotions data and description [here](https://github.com/google-research/google-research/tree/master/goemotions).

We aim to be switching around our models according to what's currently one of the best for the task - and we didn't really know how much people would care about seeing more technical details.

It sounds like you'd find it helpful to know more in-depth details about the models used for tasks.

Your feedback about what you think would be useful to have is very helpful!
- Kristo

**Comment by chiragsanghvi10** [comment]
Hey Kristo,

Thanks a lot for sharing the link of GoEmotions and for quick response as well. :)

Assuming it would be very helpful if you share the resources, mainly for down-stream task training, so I can customise the data as required. I am also following your documentation, but could not find enough details. 

Chirag Sanghvi

**Comment by LaCavao** [comment]
Hey Chirag -- we're starting work on some more advanced documentation that covers technical details + resources for our included tasks.

Thanks again for the feedback!

Owen

**Comment by chiragsanghvi10** [comment]
Hey Owen, 

I am glad to hear this. looking forward to it :) 

Many many thanks. Cheers :+1:
