### ISSUE TITLE
self._tokenizer.no_truncation() RuntimeError: Already borrowed`

### ISSUE THREAD

**Issue by chiragsanghvi10** [kiri-ai/kiri#8]
Hi, 

I am running the emotion service on cuda and I get this following RuntimeError:

```
I am sending a batch_size of 256 to extract emotions.
and generate(text, do_sample=False, max_length=512)
Is this something related to max seq length?
```

> File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/root/sales_emotion/main.py", line 34, in task_level_emotion
>     response = emotion_task_to_db(task_id)
>   File "/root/sales_emotion/src/services/emotion_task_level.py", line 67, in emotion_task_to_db
>     df_insert = task_level_emo(task_id)
>   File "/root/sales_emotion/src/services/emotion_task_level.py", line 40, in task_level_emo
>     emotion_labels.extend(kiri.emotion(text))
>   File "/root/sales_emotion/core.py", line 50, in emotion
>     return self._emotion(input_text)
>   File "/root/sales_emotion/models/tasks/emotion.py", line 42, in __call__
>     return self.model.emotion(text)
>   File "/root/sales_emotion/models/custom_models.py", line 25, in emotion
>     return self.generate(text, do_sample=False, max_length=512)
>   File "/root/sales_emotion/models/models.py", line 138, in generate
>     features = self.tokenizer(text, return_tensors="pt")
>   File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2356, in __call__
>     **kwargs,
>   File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2426, in encode_plus
>     **kwargs,
>   File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 465, in _encode_plus
>     **kwargs,
>   File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 372, in _batch_encode_plus
>     pad_to_multiple_of=pad_to_multiple_of,
>   File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 325, in set_truncation_and_paddi
> ng
>     self._tokenizer.no_truncation()
> RuntimeError: Already borrowed

Please help.

Chirag Sanghvi

**Comment by chiragsanghvi10** [comment]
Hi, this is on GPU.

**Comment by ojasaar** [comment]
Hi,

How exactly are you calling this?
For example, if I do

```python
kiri.emotion(["hello"] * 256)
```

it works fine.

If this doesn't work for you, perhaps there is a version conflict between transformers/tokenizers?

Kristo

**Comment by chiragsanghvi10** [comment]
Hi Kristo, 

It works, I was facing some issues with gunicorn workers and threads. 

But I am able to deploy the emotion with only 5 workers on 12 GB GPU.. 
Single worker takes 2.2 GB memory on GPU

any idea on the configuration bit ? 

Chirag

**Comment by chiragsanghvi10** [comment]
Hi,

Here is the solution to this..
```

tokenizer = AutoTokenizer.from_pretrained(model_name)

to

tokenizer = AutoTokenizer.from_pretrained(model_name, **use_fast=False**)

```
https://github.com/huggingface/tokenizers/issues/537

Cheers,
Chirag

**Comment by MyBruso** [comment]
> Hi,
> 
> Here is the solution to this..
> 
> ```
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name)
> 
> to
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name, **use_fast=False**)
> ```
> 
> [huggingface/tokenizers#537](https://github.com/huggingface/tokenizers/issues/537)
> 
> Cheers,
> Chirag

Hello @chiragsanghvi10 , with '**use_fast=False**', are you able to invoke  AutoTokenizer.from_pretrained() from multiple threads?

**Comment by chiragsanghvi10** [comment]
Hi @MyBruso, 

yes I am able to execute this on multiple threads with **use_fast=False**

Thanks,
